# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fenetre_principale_depos7.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 549)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fenetre_ppale = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fenetre_ppale.sizePolicy().hasHeightForWidth())
        self.fenetre_ppale.setSizePolicy(sizePolicy)
        self.fenetre_ppale.setObjectName("fenetre_ppale")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setStyleSheet("QProgressBar:vertical {\n"
"border: 1px solid gray;\n"
"border-radius: 3px;\n"
"background: white;\n"
"padding: 1px;\n"
"}\n"
"\n"
"QProgressBar::chunk:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0.5, x2: 1, y2: 0.5, stop: 0 green, stop: 1 white);\n"
"}")
        self.progressBar.setProperty("value", 25)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(True)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_3.addWidget(self.progressBar)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.suivi_circuits = QgsCollapsibleGroupBox(self.tab)
        self.suivi_circuits.setCollapsed(False)
        self.suivi_circuits.setObjectName("suivi_circuits")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.suivi_circuits)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.checkBox_ad_zst = QtWidgets.QCheckBox(self.suivi_circuits)
        self.checkBox_ad_zst.setObjectName("checkBox_ad_zst")
        self.verticalLayout_14.addWidget(self.checkBox_ad_zst)
        self.checkBox_zst_isdnd = QtWidgets.QCheckBox(self.suivi_circuits)
        self.checkBox_zst_isdnd.setObjectName("checkBox_zst_isdnd")
        self.verticalLayout_14.addWidget(self.checkBox_zst_isdnd)
        self.verticalLayout_2.addWidget(self.suivi_circuits)
        self.suivi_zones_depot = QgsCollapsibleGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.suivi_zones_depot.sizePolicy().hasHeightForWidth())
        self.suivi_zones_depot.setSizePolicy(sizePolicy)
        self.suivi_zones_depot.setAccessibleName("")
        self.suivi_zones_depot.setObjectName("suivi_zones_depot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.suivi_zones_depot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.suivi_ad = QtWidgets.QLabel(self.suivi_zones_depot)
        self.suivi_ad.setWordWrap(True)
        self.suivi_ad.setObjectName("suivi_ad")
        self.horizontalLayout_23.addWidget(self.suivi_ad)
        self.suivi_couche_ad = QgsMapLayerComboBox(self.suivi_zones_depot)
        self.suivi_couche_ad.setEnabled(False)
        self.suivi_couche_ad.setAllowEmptyLayer(True)
        self.suivi_couche_ad.setObjectName("suivi_couche_ad")
        self.horizontalLayout_23.addWidget(self.suivi_couche_ad)
        self.label_20 = QtWidgets.QLabel(self.suivi_zones_depot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_23.addWidget(self.label_20)
        self.pushButton = QtWidgets.QPushButton(self.suivi_zones_depot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_23.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.label_3 = QtWidgets.QLabel(self.suivi_zones_depot)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.suivizst = QtWidgets.QLabel(self.suivi_zones_depot)
        self.suivizst.setWordWrap(True)
        self.suivizst.setObjectName("suivizst")
        self.horizontalLayout_27.addWidget(self.suivizst)
        self.suivi_couche_zst = QgsMapLayerComboBox(self.suivi_zones_depot)
        self.suivi_couche_zst.setEnabled(False)
        self.suivi_couche_zst.setAllowEmptyLayer(True)
        self.suivi_couche_zst.setObjectName("suivi_couche_zst")
        self.horizontalLayout_27.addWidget(self.suivi_couche_zst)
        self.label_21 = QtWidgets.QLabel(self.suivi_zones_depot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_27.addWidget(self.label_21)
        self.pushButton_2 = QtWidgets.QPushButton(self.suivi_zones_depot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_27.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.suivi_isdnd = QtWidgets.QLabel(self.suivi_zones_depot)
        self.suivi_isdnd.setObjectName("suivi_isdnd")
        self.horizontalLayout_28.addWidget(self.suivi_isdnd)
        self.suivi_couche_exutoire = QgsMapLayerComboBox(self.suivi_zones_depot)
        self.suivi_couche_exutoire.setEnabled(False)
        self.suivi_couche_exutoire.setAllowEmptyLayer(True)
        self.suivi_couche_exutoire.setObjectName("suivi_couche_exutoire")
        self.horizontalLayout_28.addWidget(self.suivi_couche_exutoire)
        self.label_22 = QtWidgets.QLabel(self.suivi_zones_depot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_28.addWidget(self.label_22)
        self.pushButton_3 = QtWidgets.QPushButton(self.suivi_zones_depot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_28.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.verticalLayout_2.addWidget(self.suivi_zones_depot)
        self.mGroupBox = QgsCollapsibleGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupBox.sizePolicy().hasHeightForWidth())
        self.mGroupBox.setSizePolicy(sizePolicy)
        self.mGroupBox.setCollapsed(False)
        self.mGroupBox.setObjectName("mGroupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mGroupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.partition_radio_on = QtWidgets.QRadioButton(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partition_radio_on.sizePolicy().hasHeightForWidth())
        self.partition_radio_on.setSizePolicy(sizePolicy)
        self.partition_radio_on.setObjectName("partition_radio_on")
        self.horizontalLayout.addWidget(self.partition_radio_on)
        self.partition_radio_off = QtWidgets.QRadioButton(self.mGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partition_radio_off.sizePolicy().hasHeightForWidth())
        self.partition_radio_off.setSizePolicy(sizePolicy)
        self.partition_radio_off.setCheckable(True)
        self.partition_radio_off.setChecked(True)
        self.partition_radio_off.setObjectName("partition_radio_off")
        self.horizontalLayout.addWidget(self.partition_radio_off)
        self.pushButton_6 = QtWidgets.QPushButton(self.mGroupBox)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.command_param_durees = QtWidgets.QCommandLinkButton(self.mGroupBox)
        self.command_param_durees.setObjectName("command_param_durees")
        self.verticalLayout_10.addWidget(self.command_param_durees)
        self.verticalLayout_2.addWidget(self.mGroupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_simul = QtWidgets.QPushButton(self.tab)
        self.pushButton_simul.setEnabled(True)
        self.pushButton_simul.setObjectName("pushButton_simul")
        self.horizontalLayout_2.addWidget(self.pushButton_simul)
        self.command_voir_resultats_simu = QtWidgets.QCommandLinkButton(self.tab)
        self.command_voir_resultats_simu.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_voir_resultats_simu.sizePolicy().hasHeightForWidth())
        self.command_voir_resultats_simu.setSizePolicy(sizePolicy)
        self.command_voir_resultats_simu.setObjectName("command_voir_resultats_simu")
        self.horizontalLayout_2.addWidget(self.command_voir_resultats_simu)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.fenetre_ppale.addTab(self.tab, "")
        self.tab_durees = QtWidgets.QWidget()
        self.tab_durees.setStyleSheet("QWidget { background-color: white }")
        self.tab_durees.setObjectName("tab_durees")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_durees)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_67 = QtWidgets.QLabel(self.tab_durees)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_13.addWidget(self.label_67)
        self.toolBox = QtWidgets.QToolBox(self.tab_durees)
        self.toolBox.setStyleSheet("QToolBox { background-color: white ;}\n"
"\n"
"QToolBox::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border-radius: 5px;\n"
"    font : bold;\n"
"    color: darkgray;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    font: bold italic;\n"
"    color: black;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 635, 363))
        self.page.setObjectName("page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_38.addWidget(self.label_8)
        self.input_layer_ad_zst = QgsMapLayerComboBox(self.page)
        self.input_layer_ad_zst.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_layer_ad_zst.sizePolicy().hasHeightForWidth())
        self.input_layer_ad_zst.setSizePolicy(sizePolicy)
        self.input_layer_ad_zst.setAllowEmptyLayer(True)
        self.input_layer_ad_zst.setObjectName("input_layer_ad_zst")
        self.horizontalLayout_38.addWidget(self.input_layer_ad_zst)
        self.pushButtonCalculCheminVersZST = QtWidgets.QPushButton(self.page)
        self.pushButtonCalculCheminVersZST.setObjectName("pushButtonCalculCheminVersZST")
        self.horizontalLayout_38.addWidget(self.pushButtonCalculCheminVersZST)
        self.gridLayout_3.addLayout(self.horizontalLayout_38, 0, 1, 1, 2)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_62 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_36.addWidget(self.label_62)
        self.input_duree_base_dechgt = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_duree_base_dechgt.sizePolicy().hasHeightForWidth())
        self.input_duree_base_dechgt.setSizePolicy(sizePolicy)
        self.input_duree_base_dechgt.setProperty("value", 1.5)
        self.input_duree_base_dechgt.setObjectName("input_duree_base_dechgt")
        self.horizontalLayout_36.addWidget(self.input_duree_base_dechgt)
        self.verticalLayout_17.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.check_duree_selon_volume_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.check_duree_selon_volume_2.setObjectName("check_duree_selon_volume_2")
        self.horizontalLayout_37.addWidget(self.check_duree_selon_volume_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_37)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 17, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 2, 1)
        self.label_64 = QtWidgets.QLabel(self.groupBox_6)
        self.label_64.setEnabled(False)
        self.label_64.setObjectName("label_64")
        self.gridLayout_2.addWidget(self.label_64, 1, 1, 1, 1)
        self.input_duree_max_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.input_duree_max_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_duree_max_4.sizePolicy().hasHeightForWidth())
        self.input_duree_max_4.setSizePolicy(sizePolicy)
        self.input_duree_max_4.setObjectName("input_duree_max_4")
        self.gridLayout_2.addWidget(self.input_duree_max_4, 1, 2, 1, 1)
        self.input_duree_min_4 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.input_duree_min_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_duree_min_4.sizePolicy().hasHeightForWidth())
        self.input_duree_min_4.setSizePolicy(sizePolicy)
        self.input_duree_min_4.setObjectName("input_duree_min_4")
        self.gridLayout_2.addWidget(self.input_duree_min_4, 0, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox_6)
        self.label_63.setEnabled(False)
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 0, 1, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_2)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.checkBox_duree_reduite_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_duree_reduite_4.setObjectName("checkBox_duree_reduite_4")
        self.horizontalLayout_39.addWidget(self.checkBox_duree_reduite_4)
        self.verticalLayout_17.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem2)
        self.label_12 = QtWidgets.QLabel(self.groupBox_6)
        self.label_12.setEnabled(False)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_40.addWidget(self.label_12)
        self.input_layer_zst_2 = QgsMapLayerComboBox(self.groupBox_6)
        self.input_layer_zst_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_layer_zst_2.sizePolicy().hasHeightForWidth())
        self.input_layer_zst_2.setSizePolicy(sizePolicy)
        self.input_layer_zst_2.setObjectName("input_layer_zst_2")
        self.horizontalLayout_40.addWidget(self.input_layer_zst_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_40)
        self.filtrer_par_attribut2_7 = QtWidgets.QHBoxLayout()
        self.filtrer_par_attribut2_7.setObjectName("filtrer_par_attribut2_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.filtrer_par_attribut2_7.addItem(spacerItem3)
        self.label_65 = QtWidgets.QLabel(self.groupBox_6)
        self.label_65.setEnabled(False)
        self.label_65.setObjectName("label_65")
        self.filtrer_par_attribut2_7.addWidget(self.label_65)
        self.mFieldExpressionWidget_7 = QgsFieldExpressionWidget(self.groupBox_6)
        self.mFieldExpressionWidget_7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mFieldExpressionWidget_7.sizePolicy().hasHeightForWidth())
        self.mFieldExpressionWidget_7.setSizePolicy(sizePolicy)
        self.mFieldExpressionWidget_7.setObjectName("mFieldExpressionWidget_7")
        self.filtrer_par_attribut2_7.addWidget(self.mFieldExpressionWidget_7)
        self.verticalLayout_17.addLayout(self.filtrer_par_attribut2_7)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem4)
        self.label_66 = QtWidgets.QLabel(self.groupBox_6)
        self.label_66.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_41.addWidget(self.label_66)
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_25.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_25.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_25.setSizePolicy(sizePolicy)
        self.doubleSpinBox_25.setProperty("value", 0.3)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.horizontalLayout_41.addWidget(self.doubleSpinBox_25)
        self.verticalLayout_17.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem5)
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_42.addWidget(self.checkBox_18)
        self.verticalLayout_17.addLayout(self.horizontalLayout_42)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.page)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 3, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.chgt_duree_base = QtWidgets.QHBoxLayout()
        self.chgt_duree_base.setObjectName("chgt_duree_base")
        self.label_53 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_53.setObjectName("label_53")
        self.chgt_duree_base.addWidget(self.label_53)
        self.input_chgt_duree_base = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_chgt_duree_base.sizePolicy().hasHeightForWidth())
        self.input_chgt_duree_base.setSizePolicy(sizePolicy)
        self.input_chgt_duree_base.setProperty("value", 1.5)
        self.input_chgt_duree_base.setObjectName("input_chgt_duree_base")
        self.chgt_duree_base.addWidget(self.input_chgt_duree_base)
        self.verticalLayout_11.addLayout(self.chgt_duree_base)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.check_duree_selon_volume = QtWidgets.QCheckBox(self.groupBox_5)
        self.check_duree_selon_volume.setObjectName("check_duree_selon_volume")
        self.horizontalLayout_29.addWidget(self.check_duree_selon_volume)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.input_duree_min = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.input_duree_min.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_duree_min.sizePolicy().hasHeightForWidth())
        self.input_duree_min.setSizePolicy(sizePolicy)
        self.input_duree_min.setObjectName("input_duree_min")
        self.gridLayout.addWidget(self.input_duree_min, 0, 2, 1, 1)
        self.input_duree_max = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.input_duree_max.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_duree_max.sizePolicy().hasHeightForWidth())
        self.input_duree_max.setSizePolicy(sizePolicy)
        self.input_duree_max.setObjectName("input_duree_max")
        self.gridLayout.addWidget(self.input_duree_max, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 0, 2, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_5)
        self.label_54.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 0, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBox_5)
        self.label_55.setEnabled(False)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.checkBox_duree_reduite = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_duree_reduite.setObjectName("checkBox_duree_reduite")
        self.horizontalLayout_30.addWidget(self.checkBox_duree_reduite)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem7)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setEnabled(False)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_31.addWidget(self.label_9)
        self.input_layer_ad_2 = QgsMapLayerComboBox(self.groupBox_5)
        self.input_layer_ad_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_layer_ad_2.sizePolicy().hasHeightForWidth())
        self.input_layer_ad_2.setSizePolicy(sizePolicy)
        self.input_layer_ad_2.setObjectName("input_layer_ad_2")
        self.horizontalLayout_31.addWidget(self.input_layer_ad_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.filtrer_par_attribut2_6 = QtWidgets.QHBoxLayout()
        self.filtrer_par_attribut2_6.setObjectName("filtrer_par_attribut2_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.filtrer_par_attribut2_6.addItem(spacerItem8)
        self.label_59 = QtWidgets.QLabel(self.groupBox_5)
        self.label_59.setEnabled(False)
        self.label_59.setObjectName("label_59")
        self.filtrer_par_attribut2_6.addWidget(self.label_59)
        self.input_filter_attr_2 = QgsFieldExpressionWidget(self.groupBox_5)
        self.input_filter_attr_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_filter_attr_2.sizePolicy().hasHeightForWidth())
        self.input_filter_attr_2.setSizePolicy(sizePolicy)
        self.input_filter_attr_2.setObjectName("input_filter_attr_2")
        self.filtrer_par_attribut2_6.addWidget(self.input_filter_attr_2)
        self.verticalLayout_11.addLayout(self.filtrer_par_attribut2_6)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem9)
        self.label_60 = QtWidgets.QLabel(self.groupBox_5)
        self.label_60.setEnabled(False)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_35.addWidget(self.label_60)
        self.input_duree_reduite_2 = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.input_duree_reduite_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_duree_reduite_2.sizePolicy().hasHeightForWidth())
        self.input_duree_reduite_2.setSizePolicy(sizePolicy)
        self.input_duree_reduite_2.setProperty("value", 0.3)
        self.input_duree_reduite_2.setObjectName("input_duree_reduite_2")
        self.horizontalLayout_35.addWidget(self.input_duree_reduite_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_35)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 614, 363))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout_13.addWidget(self.toolBox)
        self.fenetre_ppale.addTab(self.tab_durees, "")
        self.tab3_result = QtWidgets.QWidget()
        self.tab3_result.setObjectName("tab3_result")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab3_result)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.parametres = QtWidgets.QGroupBox(self.tab3_result)
        self.parametres.setObjectName("parametres")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.parametres)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.groupBox = QtWidgets.QGroupBox(self.parametres)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.durees_op = QtWidgets.QLabel(self.groupBox)
        self.durees_op.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.durees_op.setObjectName("durees_op")
        self.verticalLayout_5.addWidget(self.durees_op)
        self.horizontalLayout_22.addWidget(self.groupBox)
        self.line_3 = QtWidgets.QFrame(self.parametres)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_22.addWidget(self.line_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.parametres)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.acteur = QtWidgets.QLabel(self.groupBox_2)
        self.acteur.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.acteur.setObjectName("acteur")
        self.verticalLayout_6.addWidget(self.acteur)
        self.horizontalLayout_22.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.parametres)
        self.resultats = QtWidgets.QGroupBox(self.tab3_result)
        self.resultats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.resultats.setObjectName("resultats")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.resultats)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.duree_collecte = QtWidgets.QLabel(self.resultats)
        self.duree_collecte.setText("")
        self.duree_collecte.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.duree_collecte.setObjectName("duree_collecte")
        self.verticalLayout_4.addWidget(self.duree_collecte)
        self.verticalLayout_3.addWidget(self.resultats)
        self.fenetre_ppale.addTab(self.tab3_result, "")
        self.tab4_visu = QtWidgets.QWidget()
        self.tab4_visu.setObjectName("tab4_visu")
        self.fenetre_ppale.addTab(self.tab4_visu, "")
        self.tab2_aide = QtWidgets.QWidget()
        self.tab2_aide.setObjectName("tab2_aide")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab2_aide)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fenetre_ppale.addTab(self.tab2_aide, "")
        self.verticalLayout_12.addWidget(self.fenetre_ppale)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 21))
        self.menubar.setObjectName("menubar")
        self.menuAide_la_simulation = QtWidgets.QMenu(self.menubar)
        self.menuAide_la_simulation.setObjectName("menuAide_la_simulation")
        self.menuAires_de_d_pose = QtWidgets.QMenu(self.menuAide_la_simulation)
        self.menuAires_de_d_pose.setObjectName("menuAires_de_d_pose")
        self.menuLocalisation_2 = QtWidgets.QMenu(self.menuAires_de_d_pose)
        self.menuLocalisation_2.setObjectName("menuLocalisation_2")
        self.menuAnalyse_2 = QtWidgets.QMenu(self.menuAires_de_d_pose)
        self.menuAnalyse_2.setObjectName("menuAnalyse_2")
        self.menuAnalyse_spatiale = QtWidgets.QMenu(self.menuAires_de_d_pose)
        self.menuAnalyse_spatiale.setObjectName("menuAnalyse_spatiale")
        self.menuZones_de_stockage_temporaire = QtWidgets.QMenu(self.menuAide_la_simulation)
        self.menuZones_de_stockage_temporaire.setObjectName("menuZones_de_stockage_temporaire")
        self.menuLocalisation = QtWidgets.QMenu(self.menuZones_de_stockage_temporaire)
        self.menuLocalisation.setObjectName("menuLocalisation")
        self.menuAnalyse_spatiale_2 = QtWidgets.QMenu(self.menuZones_de_stockage_temporaire)
        self.menuAnalyse_spatiale_2.setObjectName("menuAnalyse_spatiale_2")
        self.menuAnalyse_statistique = QtWidgets.QMenu(self.menuZones_de_stockage_temporaire)
        self.menuAnalyse_statistique.setObjectName("menuAnalyse_statistique")
        self.menuInstallations_de_stockage_de_d_chets_non_dangereux_ISDND = QtWidgets.QMenu(self.menuAide_la_simulation)
        self.menuInstallations_de_stockage_de_d_chets_non_dangereux_ISDND.setObjectName("menuInstallations_de_stockage_de_d_chets_non_dangereux_ISDND")
        self.menuGisements_de_dechets = QtWidgets.QMenu(self.menubar)
        self.menuGisements_de_dechets.setObjectName("menuGisements_de_dechets")
        self.menuV_hicules_de_collecte = QtWidgets.QMenu(self.menubar)
        self.menuV_hicules_de_collecte.setObjectName("menuV_hicules_de_collecte")
        self.menuGestion_du_territoire = QtWidgets.QMenu(self.menubar)
        self.menuGestion_du_territoire.setObjectName("menuGestion_du_territoire")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSaisir_de_nouvelles_zones = QtWidgets.QAction(MainWindow)
        self.actionSaisir_de_nouvelles_zones.setObjectName("actionSaisir_de_nouvelles_zones")
        self.actionLocaliser_de_nouvelles_zones = QtWidgets.QAction(MainWindow)
        self.actionLocaliser_de_nouvelles_zones.setObjectName("actionLocaliser_de_nouvelles_zones")
        self.actionComparer_deux_zones = QtWidgets.QAction(MainWindow)
        self.actionComparer_deux_zones.setObjectName("actionComparer_deux_zones")
        self.actionOptimiser_le_nombre = QtWidgets.QAction(MainWindow)
        self.actionOptimiser_le_nombre.setObjectName("actionOptimiser_le_nombre")
        self.actionVolumes_de_d_chets = QtWidgets.QAction(MainWindow)
        self.actionVolumes_de_d_chets.setObjectName("actionVolumes_de_d_chets")
        self.actionLocaliser_selon_des_crit_res = QtWidgets.QAction(MainWindow)
        self.actionLocaliser_selon_des_crit_res.setObjectName("actionLocaliser_selon_des_crit_res")
        self.actionD_finir_les_bassins_de_collecte = QtWidgets.QAction(MainWindow)
        self.actionD_finir_les_bassins_de_collecte.setObjectName("actionD_finir_les_bassins_de_collecte")
        self.actionDans_un_bassin_de_collecte = QtWidgets.QAction(MainWindow)
        self.actionDans_un_bassin_de_collecte.setObjectName("actionDans_un_bassin_de_collecte")
        self.actionDans_plusieurs_bassins_de_collecte = QtWidgets.QAction(MainWindow)
        self.actionDans_plusieurs_bassins_de_collecte.setObjectName("actionDans_plusieurs_bassins_de_collecte")
        self.actionAnalyse = QtWidgets.QAction(MainWindow)
        self.actionAnalyse.setObjectName("actionAnalyse")
        self.actionImpacts_d_ouragans = QtWidgets.QAction(MainWindow)
        self.actionImpacts_d_ouragans.setObjectName("actionImpacts_d_ouragans")
        self.actionD_chets_post_ouragans = QtWidgets.QAction(MainWindow)
        self.actionD_chets_post_ouragans.setObjectName("actionD_chets_post_ouragans")
        self.actionLocalisation_des_sources_de_d_chets_post_ouragans = QtWidgets.QAction(MainWindow)
        self.actionLocalisation_des_sources_de_d_chets_post_ouragans.setObjectName("actionLocalisation_des_sources_de_d_chets_post_ouragans")
        self.actionQuantification_des_d_chets = QtWidgets.QAction(MainWindow)
        self.actionQuantification_des_d_chets.setObjectName("actionQuantification_des_d_chets")
        self.actionAnalyse_spatiale = QtWidgets.QAction(MainWindow)
        self.actionAnalyse_spatiale.setObjectName("actionAnalyse_spatiale")
        self.actionPartitionnement_du_territoire_bassins_de_collecte = QtWidgets.QAction(MainWindow)
        self.actionPartitionnement_du_territoire_bassins_de_collecte.setObjectName("actionPartitionnement_du_territoire_bassins_de_collecte")
        self.actionCorrespondance_zones_de_chargement_d_chargement = QtWidgets.QAction(MainWindow)
        self.actionCorrespondance_zones_de_chargement_d_chargement.setObjectName("actionCorrespondance_zones_de_chargement_d_chargement")
        self.actionCalcul_des_plus_courts_chemins = QtWidgets.QAction(MainWindow)
        self.actionCalcul_des_plus_courts_chemins.setObjectName("actionCalcul_des_plus_courts_chemins")
        self.actionDensit_des_AD = QtWidgets.QAction(MainWindow)
        self.actionDensit_des_AD.setObjectName("actionDensit_des_AD")
        self.actionD_finir_les_caract_ristiques = QtWidgets.QAction(MainWindow)
        self.actionD_finir_les_caract_ristiques.setObjectName("actionD_finir_les_caract_ristiques")
        self.actionAffecter_les_bassins_de_collecte = QtWidgets.QAction(MainWindow)
        self.actionAffecter_les_bassins_de_collecte.setObjectName("actionAffecter_les_bassins_de_collecte")
        self.actionVolumes_de_d_chets_2 = QtWidgets.QAction(MainWindow)
        self.actionVolumes_de_d_chets_2.setObjectName("actionVolumes_de_d_chets_2")
        self.actionDensit_des_ZST = QtWidgets.QAction(MainWindow)
        self.actionDensit_des_ZST.setObjectName("actionDensit_des_ZST")
        self.actionSaisir_des_zones = QtWidgets.QAction(MainWindow)
        self.actionSaisir_des_zones.setObjectName("actionSaisir_des_zones")
        self.actionSaisir_des_zones_2 = QtWidgets.QAction(MainWindow)
        self.actionSaisir_des_zones_2.setObjectName("actionSaisir_des_zones_2")
        self.menuLocalisation_2.addAction(self.actionSaisir_des_zones_2)
        self.menuLocalisation_2.addAction(self.actionLocaliser_selon_des_crit_res)
        self.menuAnalyse_2.addAction(self.actionVolumes_de_d_chets)
        self.menuAnalyse_spatiale.addAction(self.actionDensit_des_AD)
        self.menuAires_de_d_pose.addAction(self.menuLocalisation_2.menuAction())
        self.menuAires_de_d_pose.addAction(self.menuAnalyse_2.menuAction())
        self.menuAires_de_d_pose.addAction(self.menuAnalyse_spatiale.menuAction())
        self.menuLocalisation.addAction(self.actionSaisir_de_nouvelles_zones)
        self.menuLocalisation.addAction(self.actionLocaliser_de_nouvelles_zones)
        self.menuAnalyse_spatiale_2.addAction(self.actionComparer_deux_zones)
        self.menuAnalyse_spatiale_2.addAction(self.actionOptimiser_le_nombre)
        self.menuAnalyse_spatiale_2.addAction(self.actionDensit_des_ZST)
        self.menuAnalyse_statistique.addAction(self.actionVolumes_de_d_chets_2)
        self.menuZones_de_stockage_temporaire.addAction(self.menuLocalisation.menuAction())
        self.menuZones_de_stockage_temporaire.addAction(self.menuAnalyse_statistique.menuAction())
        self.menuZones_de_stockage_temporaire.addAction(self.menuAnalyse_spatiale_2.menuAction())
        self.menuInstallations_de_stockage_de_d_chets_non_dangereux_ISDND.addAction(self.actionSaisir_des_zones)
        self.menuAide_la_simulation.addAction(self.menuAires_de_d_pose.menuAction())
        self.menuAide_la_simulation.addAction(self.menuZones_de_stockage_temporaire.menuAction())
        self.menuAide_la_simulation.addAction(self.menuInstallations_de_stockage_de_d_chets_non_dangereux_ISDND.menuAction())
        self.menuGisements_de_dechets.addAction(self.actionLocalisation_des_sources_de_d_chets_post_ouragans)
        self.menuGisements_de_dechets.addAction(self.actionQuantification_des_d_chets)
        self.menuGisements_de_dechets.addAction(self.actionAnalyse)
        self.menuGisements_de_dechets.addAction(self.actionAnalyse_spatiale)
        self.menuV_hicules_de_collecte.addAction(self.actionD_finir_les_caract_ristiques)
        self.menuV_hicules_de_collecte.addAction(self.actionAffecter_les_bassins_de_collecte)
        self.menuGestion_du_territoire.addAction(self.actionPartitionnement_du_territoire_bassins_de_collecte)
        self.menuGestion_du_territoire.addAction(self.actionCorrespondance_zones_de_chargement_d_chargement)
        self.menuGestion_du_territoire.addAction(self.actionCalcul_des_plus_courts_chemins)
        self.menubar.addAction(self.menuGisements_de_dechets.menuAction())
        self.menubar.addAction(self.menuAide_la_simulation.menuAction())
        self.menubar.addAction(self.menuGestion_du_territoire.menuAction())
        self.menubar.addAction(self.menuV_hicules_de_collecte.menuAction())

        self.retranslateUi(MainWindow)
        self.fenetre_ppale.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.checkBox_ad_zst.clicked['bool'].connect(self.suivi_couche_ad.setEnabled)
        self.checkBox_ad_zst.clicked['bool'].connect(self.suivi_couche_zst.setEnabled)
        self.checkBox_zst_isdnd.clicked['bool'].connect(self.suivi_couche_zst.setEnabled)
        self.checkBox_zst_isdnd.clicked['bool'].connect(self.suivi_couche_exutoire.setEnabled)
        self.checkBox_ad_zst.clicked['bool'].connect(self.label_8.setEnabled)
        self.checkBox_ad_zst.clicked['bool'].connect(self.input_layer_ad_zst.setEnabled)
        self.check_duree_selon_volume.clicked['bool'].connect(self.label_54.setEnabled)
        self.check_duree_selon_volume.clicked['bool'].connect(self.label_55.setEnabled)
        self.check_duree_selon_volume.clicked['bool'].connect(self.input_duree_min.setEnabled)
        self.check_duree_selon_volume.clicked['bool'].connect(self.input_duree_max.setEnabled)
        self.checkBox_duree_reduite.clicked['bool'].connect(self.label_60.setEnabled)
        self.checkBox_duree_reduite.clicked['bool'].connect(self.input_duree_reduite_2.setEnabled)
        self.checkBox_duree_reduite.clicked['bool'].connect(self.label_9.setEnabled)
        self.checkBox_duree_reduite.clicked['bool'].connect(self.input_layer_ad_2.setEnabled)
        self.checkBox_duree_reduite.clicked['bool'].connect(self.label_59.setEnabled)
        self.checkBox_duree_reduite.clicked['bool'].connect(self.input_filter_attr_2.setEnabled)
        self.check_duree_selon_volume_2.clicked['bool'].connect(self.label_63.setEnabled)
        self.check_duree_selon_volume_2.clicked['bool'].connect(self.input_duree_min_4.setEnabled)
        self.check_duree_selon_volume_2.clicked['bool'].connect(self.label_64.setEnabled)
        self.check_duree_selon_volume_2.clicked['bool'].connect(self.input_duree_max_4.setEnabled)
        self.checkBox_duree_reduite_4.clicked['bool'].connect(self.label_12.setEnabled)
        self.checkBox_duree_reduite_4.clicked['bool'].connect(self.input_layer_zst_2.setEnabled)
        self.checkBox_duree_reduite_4.clicked['bool'].connect(self.label_65.setEnabled)
        self.checkBox_duree_reduite_4.clicked['bool'].connect(self.mFieldExpressionWidget_7.setEnabled)
        self.checkBox_duree_reduite_4.clicked['bool'].connect(self.label_66.setEnabled)
        self.checkBox_duree_reduite_4.clicked['bool'].connect(self.doubleSpinBox_25.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DéPOs - Fenêtre principale"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Progression du paramétrage</span></p></body></html>"))
        self.suivi_circuits.setTitle(_translate("MainWindow", "0. Circuit de collecte à simuler"))
        self.checkBox_ad_zst.setText(_translate("MainWindow", "Gisements -> Installations temporaires de transit"))
        self.checkBox_zst_isdnd.setText(_translate("MainWindow", "Installations temporaires de transit > Exutoires"))
        self.suivi_zones_depot.setTitle(_translate("MainWindow", "1. Zones de dépôt"))
        self.suivi_ad.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Gisements de déchets à collecter</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "ou"))
        self.pushButton.setText(_translate("MainWindow", "Générer la couche"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#00557f;\">Un </span><span style=\" font-weight:600; font-style:italic; color:#00557f;\">gisement de déchet</span><span style=\" font-style:italic; color:#00557f;\"> correspond au lieu où :<br/>- le déchet a été produit (exemple : au niveau du bâtiment)<br/>- le déchet a été déposé en vue de son transfert vers une installation temporaire de transit</span></p></body></html>"))
        self.suivizst.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Installations temporaires de transit</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "ou"))
        self.pushButton_2.setText(_translate("MainWindow", "Générer la couche"))
        self.suivi_isdnd.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Exutoires</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "ou"))
        self.pushButton_3.setText(_translate("MainWindow", "Générer la couche"))
        self.mGroupBox.setTitle(_translate("MainWindow", "2. Gestion du territoire (existence de plusieurs bassins de collecte)"))
        self.label.setText(_translate("MainWindow", "Plusieurs bassins de collecte ?"))
        self.partition_radio_on.setText(_translate("MainWindow", "Oui"))
        self.partition_radio_off.setText(_translate("MainWindow", "Non"))
        self.pushButton_6.setText(_translate("MainWindow", "Définir la gestion de la collecte..."))
        self.command_param_durees.setText(_translate("MainWindow", "3. Paramétrer les durées de collecte"))
        self.pushButton_simul.setText(_translate("MainWindow", "Lancer la simulation"))
        self.command_voir_resultats_simu.setText(_translate("MainWindow", "Voir les résultats"))
        self.fenetre_ppale.setTabText(self.fenetre_ppale.indexOf(self.tab), _translate("MainWindow", "Paramétrage"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Durées des opérations de chargement / déchargement</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "Chemins Gisements -> ZST"))
        self.pushButtonCalculCheminVersZST.setText(_translate("MainWindow", "Calculer les chemins"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Déchargement"))
        self.label_62.setText(_translate("MainWindow", "Durée de déchargement par défaut (h) :"))
        self.check_duree_selon_volume_2.setText(_translate("MainWindow", "Proportionnelle aux volumes de déchets à décharger"))
        self.label_64.setText(_translate("MainWindow", "Durée maximale (h)"))
        self.label_63.setText(_translate("MainWindow", "Durée minimale (h)"))
        self.checkBox_duree_reduite_4.setText(_translate("MainWindow", "Réduction du temps si la zone est équipée"))
        self.label_12.setText(_translate("MainWindow", "Couche des ZST"))
        self.label_65.setText(_translate("MainWindow", "Filtrer par l\'attribut:"))
        self.label_66.setText(_translate("MainWindow", "Durée dans une zone équipée (h) :"))
        self.checkBox_18.setText(_translate("MainWindow", "Pénalité due au trafic"))
        self.pushButton_5.setText(_translate("MainWindow", "Valider"))
        self.pushButton_4.setText(_translate("MainWindow", "Réinitialiser les valeurs par défaut"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Chargement"))
        self.label_53.setText(_translate("MainWindow", "Durée de chargement par défaut (h) :"))
        self.check_duree_selon_volume.setText(_translate("MainWindow", "Proportionnelle aux volumes de déchets à charger"))
        self.label_54.setText(_translate("MainWindow", "Durée minimale (h)"))
        self.label_55.setText(_translate("MainWindow", "Durée maximale (h)"))
        self.checkBox_duree_reduite.setText(_translate("MainWindow", "Réduction du temps si la zone est équipée"))
        self.label_9.setText(_translate("MainWindow", "Couche des gisements"))
        self.label_59.setText(_translate("MainWindow", "Filtrer par l\'attribut:"))
        self.label_60.setText(_translate("MainWindow", "Durée dans une zone équipée (h) :"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Aires de dépose -> Installations temporaires de transit"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Installations temporaires de transit -> Exutoires"))
        self.fenetre_ppale.setTabText(self.fenetre_ppale.indexOf(self.tab_durees), _translate("MainWindow", "Modalités de collecte"))
        self.parametres.setTitle(_translate("MainWindow", "Récapitulatif"))
        self.groupBox.setTitle(_translate("MainWindow", "Durée des opérations"))
        self.durees_op.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Acteur de collecte"))
        self.acteur.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.resultats.setTitle(_translate("MainWindow", "Durées estimées"))
        self.fenetre_ppale.setTabText(self.fenetre_ppale.indexOf(self.tab3_result), _translate("MainWindow", "Résultats"))
        self.fenetre_ppale.setTabText(self.fenetre_ppale.indexOf(self.tab4_visu), _translate("MainWindow", "Visualisation"))
        self.fenetre_ppale.setTabText(self.fenetre_ppale.indexOf(self.tab2_aide), _translate("MainWindow", "Aide"))
        self.menuAide_la_simulation.setTitle(_translate("MainWindow", "Zones de dépôt"))
        self.menuAires_de_d_pose.setTitle(_translate("MainWindow", "Aires de dépose (AD)"))
        self.menuLocalisation_2.setTitle(_translate("MainWindow", "Localisation"))
        self.menuAnalyse_2.setTitle(_translate("MainWindow", "Analyse statistique"))
        self.menuAnalyse_spatiale.setTitle(_translate("MainWindow", "Analyse spatiale"))
        self.menuZones_de_stockage_temporaire.setTitle(_translate("MainWindow", "Zones de stockage temporaire (ZST)"))
        self.menuLocalisation.setTitle(_translate("MainWindow", "Localisation"))
        self.menuAnalyse_spatiale_2.setTitle(_translate("MainWindow", "Analyse spatiale"))
        self.menuAnalyse_statistique.setTitle(_translate("MainWindow", "Analyse statistique"))
        self.menuInstallations_de_stockage_de_d_chets_non_dangereux_ISDND.setTitle(_translate("MainWindow", "Installations de stockage de déchets non dangereux (ISDND)"))
        self.menuGisements_de_dechets.setTitle(_translate("MainWindow", "Gisements de déchets"))
        self.menuV_hicules_de_collecte.setTitle(_translate("MainWindow", "Acteurs de la collecte"))
        self.menuGestion_du_territoire.setTitle(_translate("MainWindow", "Gestion du territoire"))
        self.actionSaisir_de_nouvelles_zones.setText(_translate("MainWindow", "Saisir des zones"))
        self.actionLocaliser_de_nouvelles_zones.setText(_translate("MainWindow", "Localiser selon des critères"))
        self.actionComparer_deux_zones.setText(_translate("MainWindow", "Comparer deux zones"))
        self.actionOptimiser_le_nombre.setText(_translate("MainWindow", "Optimiser le nombre de ZST"))
        self.actionVolumes_de_d_chets.setText(_translate("MainWindow", "Volumes de déchets"))
        self.actionLocaliser_selon_des_crit_res.setText(_translate("MainWindow", "Localiser selon des critères"))
        self.actionD_finir_les_bassins_de_collecte.setText(_translate("MainWindow", "Partitionner le territoire"))
        self.actionDans_un_bassin_de_collecte.setText(_translate("MainWindow", "Dans un bassin de collecte"))
        self.actionDans_plusieurs_bassins_de_collecte.setText(_translate("MainWindow", "Dans plusieurs bassins de collecte"))
        self.actionAnalyse.setText(_translate("MainWindow", "Analyse statistique"))
        self.actionImpacts_d_ouragans.setText(_translate("MainWindow", "Endommagements post-ouragans"))
        self.actionD_chets_post_ouragans.setText(_translate("MainWindow", "Déchets post-ouragans"))
        self.actionLocalisation_des_sources_de_d_chets_post_ouragans.setText(_translate("MainWindow", "Localisation des sources de déchets post-ouragans (bâtiments endommagés)"))
        self.actionQuantification_des_d_chets.setText(_translate("MainWindow", "Quantification des déchets"))
        self.actionAnalyse_spatiale.setText(_translate("MainWindow", "Analyse spatiale"))
        self.actionPartitionnement_du_territoire_bassins_de_collecte.setText(_translate("MainWindow", "Partitionnement du territoire (bassins de collecte)"))
        self.actionCorrespondance_zones_de_chargement_d_chargement.setText(_translate("MainWindow", "Correspondance zones de chargement / déchargement"))
        self.actionCalcul_des_plus_courts_chemins.setText(_translate("MainWindow", "Calcul des plus courts chemins"))
        self.actionDensit_des_AD.setText(_translate("MainWindow", "Densité des AD"))
        self.actionD_finir_les_caract_ristiques.setText(_translate("MainWindow", "Définir les caractéristiques"))
        self.actionAffecter_les_bassins_de_collecte.setText(_translate("MainWindow", "Affecter les bassins de collecte"))
        self.actionVolumes_de_d_chets_2.setText(_translate("MainWindow", "Volumes de déchets"))
        self.actionDensit_des_ZST.setText(_translate("MainWindow", "Densité des ZST"))
        self.actionSaisir_des_zones.setText(_translate("MainWindow", "Saisir des zones"))
        self.actionSaisir_des_zones_2.setText(_translate("MainWindow", "Saisir des zones"))

from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsfieldexpressionwidget import QgsFieldExpressionWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
