# -*- coding: utf-8 -*-
"""
/***************************************************************************
 simu_damage2
                                 A QGIS plugin
 Simule les endommagements post-ouragans sur une couche de bâtiments
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-17
        copyright            : (C) 2020 by QT Truong
        email                : quy-thy.truong@ifsttar.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load simu_damage2 class from file simu_damage2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .simu_damage2 import simu_damage2
    return simu_damage2(iface)
